name: Listen to Issues
on: issues
jobs:
  print-issue-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue Title and Descrption
        run: echo "Title - ${{ github.event.issue.title }}, Description - ${{ github.event.issue.body }}"
      - name: Print Issue Details
        run: echo "${{ toJSON(github) }}"